project:
  type: website
  output-dir: _site

filters:
  - filters/task.lua

website:
  title: "ML Protein Design Bootcamp 2025"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Monday"
        href: monday/index.qmd
      - text: "Tuesday"
        href: tuesday/index.qmd
      - text: "Wednesday"
        href: wednesday/index.qmd
      - text: "Thursday"
        href: thursday/index.qmd
      - text: "Capstone"
        href: capstone/index.qmd
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/RosettaMLBootCamp2025/RosettaMLBootCamp2025.github.io/issues/new
        text: Report Issue
  sidebar:
    - title: "Monday"
      contents:
        - monday/index.qmd
        - text: "---"
        - monday/0-hpc-setup.qmd
        - monday/1-localcolabfold.qmd
        - monday/2-ligandmpnn.qmd
        - monday/3-rfdiffusion2.qmd
        - monday/4-esmfold.qmd
        - monday/5-openfold.qmd
        - monday/6-chai1.qmd
        - monday/7-boltz2.qmd
        - monday/8-diffdock-pp.qmd
        - monday/9-placer.qmd
        - monday/10-bindcraft.qmd
        - text: "---"
        - monday/11-esm3.qmd
        - monday/12-rfdiffusion-aa.qmd
    - title: "Tuesday"
      contents:
        - tuesday/index.qmd
        - tuesday/2.1-placeholder.qmd
    - title: "Wednesday"
      contents:
        - wednesday/index.qmd
        - wednesday/3.1-placeholder.qmd
    - title: "Thursday"
      contents:
        - thursday/index.qmd
        - thursday/4.1-placeholder.qmd
    - title: "Capstone"
      contents:
        - capstone/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    include-after-body: _includes/progress-tracker.html
